# Generated by Django 3.2.25 on 2024-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20241127_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('IN_GAME', 'In Game'), ('AWAY', 'Away')], default='OFFLINE', max_length=20),
        ),
    ]
